name: Build and Test

on:
  workflow_dispatch:

  push:
    branches:
      - development
      - staging
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: 16.x

      - name: Cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: cache-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Install Dependencies
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: yarn install

      - name: Compile Assets
        run: yarn build
        if: steps.restore-build.outputs.cache-hit != 'true'
